### ISSUE TITLE
Adding custom logos to funkplot

### ISSUE THREAD

**Issue by tacesa** [funkyfranky/FunkMan#10]
Hi there!
Thank you for sharing your work!

I had a look at the code in funkplot.py because I thought about adding a custom watermark style logo to the grade sheets.
Since I don't really have experience in Python coding I probably did everything wrong:
- first uploaded a new .pnd into the funcpics directory
- edited the code to set an additional property:
    self.imageCustomlogo = plt.imread(ImagePath+"CustomLogo.png")
- tried to copy one of the existing plt.imshow commands
    plt.imshow(self.imageCustomLogo, interpolation='none', origin='upper', extent=[north-30, north+30, north-23, north+37], clip_on=True, zorder=18)

From that attempt I get:
    2024-05-19 22:17:05.718 ERROR   'FunkPlot' object has no attribute 'imageCustomLogo'

Appreciate every advice :-)

Cheers

Yoshi

**Comment by tacesa** [comment]
Found a solution:
`
ax.figure.figimage(self.imageCustomLogo, 20, 20, alpha=0.5, zorder=18, clip_on=True)
`

imshow could work as well but will keep the logo position related to/inside the grid (from my limited understanding).
Of course self.imageCustomLogo has to be set first hand, in my opening post a also had a typo.

Now things work as intended, hope this might be helpful for someone.

Cheers
Yoshi

**Comment by pschilly** [comment]
@tacesa 

Would you mind dropping in the exact code you used to get this to work?

I cannot seem to read where that `ax.figure.figimage(self.imageCustomLogo, 20, 20, alpha=0.5, zorder=18, clip_on=True)` should be placed?

**Comment by tacesa** [comment]
Of course.

I refined my solution a little bit, now the line of code looks like this:
`fig.figimage(self.imageFVN, 10, 10, alpha=0.5)`

Each block in the code has these two towards its end:
```
# Mission date at left bottom
...
# Real date at right bottom.
```

I put my code just before "# Mission date".

Cheers
