### ISSUE TITLE
Release height unit in meters not feet

### ISSUE THREAD

**Issue by funkyfranky** [funkyfranky/FunkMan#6]
Rob Graham — Today at 18:34
@funkyfranky noticed something tonight with the Range class, were it sends to Funkman, despite funkman saying the release heights are in Ft, they are being sent as meters and not converted.

attackAlt is stored in line 85756 of Moose.lua and at no point is a util.MetersToFeet done, nor does the bot seem to do any in funkplot.py just thought i'd let you know.
(mind my moose might be slightly out of date so if you've already noticed and fixed ignore)
having a quick look in the latest dev branch to see if the same things happening
Rob Graham — Today at 18:42
yeah range.lua 
line 2046 = local attackAlt=_unit:GetHeight() (which is returning height in meters)
that gets send to the result in weapon:setFuncImpact which doesn't seem to do any conversion. on line 2053
line 1971 result.attackAlt = attackAlt 
I can't find anyplace that its converted from the _unit:GetHeight() to ft.

**Comment by robgrahamau** [comment]
to be fair I think the errors more in Moose than funkman Franky, the moose docs state it returns feet when as far as I can see by the above, it's meters.

**Comment by robgrahamau** [comment]
can close this Franky its fixed moose side.

**Comment by funkyfranky** [comment]
Thanks
